name: Build NeoForge 1.21.1 Mod

on:
  push:
    branches: [ '1.20.1' ]  # Updated to match the 1.21.1 branch
  pull_request:
    branches: [ '1.20.1' ]
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
          
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Make gradlew executable
        run: chmod +x gradlew
        
      - name: Update Gradle wrapper to version 8.x
        run: ./gradlew wrapper --gradle-version 8.0  # Ensuring Gradle 8.x compatibility

      - name: Build with Gradle
        run: ./gradlew build --stacktrace --info
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NeoForge-1.21.1-Build
          path: build/libs/*.jar
          if-no-files-found: error
