name: Build JavaFX Project

on:
  push:
    branches: [ 1.20.1 ]
  pull_request:
    branches: [ 1.20.1 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Download and unzip JavaFX
      run: |
        wget https://download2.gluonhq.com/openjfx/21.0.2/openjfx-21.0.2_linux-x64_bin-sdk.zip
        unzip openjfx-21.0.2_linux-x64_bin-sdk.zip
        echo "JAVA_FX=$(pwd)/javafx-sdk-21.0.2/lib" >> $GITHUB_ENV

    - name: Compile the JavaFX app
      run: |
        mkdir -p out
        javac --module-path $JAVA_FX --add-modules javafx.controls,javafx.fxml \
          -d out $(find src -name "*.java")

    - name: Package into JAR
      run: |
        cd out
        jar cfe SimpleLogin.jar com.wasbanned.simplelogin.Main *

    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v3
      with:
        name: SimpleLogin
        path: out/SimpleLogin.jar
