name: Build and Test

on:
  push:
    branches: [ '1.20.1' ]
  pull_request:
    branches: [ '1.20.1' ]

jobs:
  build:
    name: Build NeoForge 1.20.1 Mod
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Minecraft 1.20.1 requires Java 17
          distribution: 'temurin'
          cache: 'gradle'
          
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Make gradlew executable
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew build --stacktrace --info
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: SimpleLogin-1.20.1-Build
          path: |
            build/libs/*.jar
          if-no-files-found: error
